### ISSUE TITLE
wrong config 

### ISSUE THREAD

**Issue by bboalimoe** [meowoodie/behaivor-streaming#1]
```
- bolt:
        name: regularization_bolt
        module: streaming_topology.regularization_bolt
        groupings:
            - shuffle_grouping:
                component: kafka_user_motion
            - shuffle_grouping:
                component: kafka_user_location
    - bolt:
        name: statistic_bolt
        module: streaming_topology.statistic_bolt
        tick_freq_secs: 30.0
        groupings:
            - fields_grouping:
                component: user_behavior_spout
                fields:
                    - userId
                    - type

```
